export enum NotificationType {
  INFO = 'INFO',
  WARNING = 'WARNING',
  ERROR = 'ERROR',
  SUCCESS = 'SUCCESS',
  QUIZ_ASSIGNED = 'QUIZ_ASSIGNED',
  EXERCISE_ASSIGNED = 'EXERCISE_ASSIGNED',
  GRADE_RELEASED = 'GRADE_RELEASED',
  DEADLINE_REMINDER = 'DEADLINE_REMINDER',
}
