name: Perf & Security Checks

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  perf-and-security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build backend image
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          push: false
          tags: tutorize-backend:perf
          load: true

      - name: Start test container
        run: |
          docker run -d --name tutorize-perf -p 3002:3000 tutorize-backend:perf || true
          sleep 5

      - name: Wait for API
        run: |
          for i in {1..20}; do
            if curl -fs http://localhost:3002/api/v1/health >/dev/null 2>&1; then
              echo "API ready"; break;
            fi
            sleep 2
          done

      - name: Run k6 load test
        run: |
          docker run --rm -v ${GITHUB_WORKSPACE}:/src -w /src grafana/k6:latest run \
            --vus 20 --duration 30s --out json=load-test/k6/results.json load-test/k6/load-test.js
        env:
          GITHUB_WORKSPACE: ${{ github.workspace }}

      - name: Upload k6 results
        uses: actions/upload-artifact@v4
        with:
          name: k6-results
          path: load-test/k6/results.json

      - name: Publish k6 metrics to Grafana
        run: |
          node load-test/k6/publish-to-grafana.js load-test/k6/results.json || true
        env:
          GRAFANA_PUSH_URL: ${{ secrets.GRAFANA_PUSH_URL }}
          GRAFANA_API_KEY: ${{ secrets.GRAFANA_API_KEY }}

      - name: Run OWASP ZAP baseline (dockerized)
        run: |
          mkdir -p zap-report
          docker run --rm -v ${GITHUB_WORKSPACE}/zap-report:/zap/wrk/:rw owasp/zap2docker-stable zap-baseline.py -t http://localhost:3002/api/v1 -r /zap/wrk/zap-report.html -J /zap/wrk/zap-report.json || true

      - name: Upload ZAP report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: zap-report/

      - name: Stop container
        if: always()
        run: |
          docker stop tutorize-perf || true
          docker rm tutorize-perf || true
